Manual state store support and Kafka client cleanups
Axual/ksml pull request #81
Opened 2023-11-03 09:46 UTC by jeroenvandisseldorp

2023-11-03 11:42 UTC, richard-axual requested changes
It looks good overall, but I think several of the proxy classes are no longer needed.

2023-11-03 11:42 UTC, richard-axual commented on ksml-data-generator/src/main/java/io/axual/ksml/datagenerator/config/ProducerConfig.java
>      public String workingDirectory;
Should we make this by default the current working directory of the process?

2023-11-03 11:42 UTC, richard-axual commented on ksml-data-generator/src/main/java/io/axual/ksml/datagenerator/factory/AxualClientFactory.txt
Shouldn't this file be deleted?

2023-11-03 11:42 UTC, richard-axual commented on ksml-kafka-clients/pom.xml
> +    <description>Client components for KSML
Maybe put a bit more information here what functionality these components offer?

2023-11-03 11:42 UTC, richard-axual commented on ksml-kafka-clients/src/main/java/io/axual/ksml/client/util/FactoryUtil.java
Why rebuild this logic here instead of using the Kafka Utils directly?.

2023-11-03 11:42 UTC, richard-axual commented on ksml-kafka-clients/src/main/java/io/axual/ksml/client/admin/ProxyAdmin.java
I think this can be removed, or replaced by the normal Kafka Admin interface, as this proxy is initialised explicitly with an already build Admin instance

2023-11-03 11:42 UTC, richard-axual commented on ksml-kafka-clients/src/main/java/io/axual/ksml/client/consumer/ProxyConsumer.java
I think this can be removed, or replaced by the normal Kafka Consumer interface, as this proxy is initialised explicitly with an already build Consumer instance

2023-11-03 11:42 UTC, richard-axual commented on ksml-kafka-clients/src/main/java/io/axual/ksml/client/producer/ProxyProducer.java
I think this can be removed, or replaced by the normal Kafka Admin interface, as this proxy is initialised explicitly with an already build Admin instance

2023-11-03 14:02 UTC, jeroenvandisseldorp commented on ksml-data-generator/src/main/java/io/axual/ksml/datagenerator/config/ProducerConfig.java
>      public String workingDirectory;
I hadn't noticed before, but there is actually a difference now between working directory and configuration directory. The working directory holds ksml-data-generator.yaml and ksml-runner.yaml, and it acts as the folder for local state store storage. The config directory holds all all .yaml files to be read (except for the ones mentioned above).

We could do like this:
- Configuration dir: contains all .yaml files, schema etcetera. Also make this the default location for ksml-runner.yaml and ksml-data-generator.yaml too. Allow to be overriden by first parameter to the executable.
- Working dir: rename to "storage dir" --> only required for runner, not for data generator

2023-11-03 14:02 UTC, jeroenvandisseldorp commented on ksml-data-generator/src/main/java/io/axual/ksml/datagenerator/factory/AxualClientFactory.txt
Yes, done

2023-11-03 14:06 UTC, jeroenvandisseldorp commented on ksml-kafka-clients/src/main/java/io/axual/ksml/client/admin/ProxyAdmin.java
The idea is that ProxyXX classes call the backing client by default. The ResolvingXX classes only override those methods that actually need to do resolving. Makes for better readability, that's all. If this is deemed over-engineered, then we could remove them.

2023-11-03 14:06 UTC, jeroenvandisseldorp commented on ksml-kafka-clients/src/main/java/io/axual/ksml/client/consumer/ProxyConsumer.java
See ProxyAdmin comment

2023-11-03 14:06 UTC, jeroenvandisseldorp commented on ksml-kafka-clients/src/main/java/io/axual/ksml/client/producer/ProxyProducer.java
See ProxyAdmin comment

2023-11-08 10:25 UTC, richard-axual commented on ksml-data-generator/src/main/java/io/axual/ksml/datagenerator/config/ProducerConfig.java
>      public String workingDirectory;
@jeroenvandisseldorp I agree with your suggestion to make config dir the container of YAMLs, Schemas etc and rename working dir to storage dir

2023-11-17 08:13 UTC, richard-axual commented on ksml-kafka-clients/src/main/java/io/axual/ksml/client/admin/ProxyAdmin.java
@jeroenvandisseldorp I think inheritance and delegate methods are overkill for this, we don't expect any other classes needing to inherit from.

2023-11-17 08:20 UTC, richard-axual commented on ksml-data-generator/src/main/java/io/axual/ksml/datagenerator/config/ProducerConfig.java
>      public String workingDirectory;
@jeroenvandisseldorp The runner configuration has been updated to the new directory structure, can you update the DataGenerator config as well?

2023-11-24 16:02 UTC, richard-axual approved these changes

2023-11-24 16:03 UTC, merged